// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Connection = __t.object("Connection", {
  id: __t.connectionId(),
  identity: __t.identity(),
});
export type Connection = __Infer<typeof Connection>;

export const ControlClock = __t.object("ControlClock", {
  key: __t.string(),
  sentAt: __t.u64(),
});
export type ControlClock = __Infer<typeof ControlClock>;

export const LobbyMember = __t.object("LobbyMember", {
  playerId: __t.string(),
  online: __t.bool(),
});
export type LobbyMember = __Infer<typeof LobbyMember>;

export const LobbyRoster = __t.object("LobbyRoster", {});
export type LobbyRoster = __Infer<typeof LobbyRoster>;

export const MatchState = __t.object("MatchState", {
  room: __t.string(),
  snapshot: __t.string(),
  revision: __t.u32(),
});
export type MatchState = __Infer<typeof MatchState>;

export const Membership = __t.object("Membership", {
  identity: __t.identity(),
  room: __t.string(),
  playerId: __t.string(),
  lastCommandMicros: __t.u64(),
});
export type Membership = __Infer<typeof Membership>;

export const MySession = __t.object("MySession", {});
export type MySession = __Infer<typeof MySession>;

export const RoomLobby = __t.object("RoomLobby", {
  room: __t.string(),
  publicMatch: __t.bool(),
  started: __t.bool(),
  hostPlayerId: __t.string(),
  readyPlayers: __t.string(),
});
export type RoomLobby = __Infer<typeof RoomLobby>;

export const RoomOwner = __t.object("RoomOwner", {
  room: __t.string(),
  identity: __t.identity(),
});
export type RoomOwner = __Infer<typeof RoomOwner>;

export const TickTimer = __t.object("TickTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TickTimer = __Infer<typeof TickTimer>;

