import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,addPlayer,applyCommand,stepGame} from './simulation';
import {canOccupy,getMoveSpeed} from './movement';
import {DASH_DAMAGE,SHOCKWAVE_DAMAGE} from './balance';

function arena(){const s=createGame('kit',2),id=addPlayer(s,{name:'Hero',hero:'knight',companion:'guardian',size:2});const hero=s.actors.find(a=>a.id===id)!;hero.x=6;hero.y=20;hero.protectedUntil=0;const enemy=s.actors.find(a=>a.team==='red')!;enemy.bot=false;enemy.protectedUntil=0;s.actors=[hero,enemy];s.structures=[];enemy.x=7.3;enemy.y=20.7;return {s,hero,enemy};}
test('dash sweeps three tiles and damages each nearby enemy once',()=>{const {s,hero,enemy}=arena();const second={...enemy,id:'second',x:8,y:19.3};s.actors.push(second);applyCommand(s,hero.id,{type:'ability',slot:1,x:9,y:20});assert.ok(Math.abs(hero.x-9)<1e-6);assert.equal(enemy.hp,enemy.maxHp-DASH_DAMAGE);assert.equal(second.hp,second.maxHp-DASH_DAMAGE);assert.equal(s.effects.at(-1)?.abilitySlot,1);});
test('dash cannot tunnel across forest boundary or a tower',()=>{const {s,hero}=arena();s.actors=[hero];hero.x=6;hero.y=20;applyCommand(s,hero.id,{type:'ability',slot:1,x:-10,y:20});assert.ok(hero.x>3);assert.ok(canOccupy(s,hero,hero.id));hero.x=6;hero.abilityCooldowns=[0,0,0];s.structures=[{id:'block',kind:'tower',team:'blue',x:8,y:20,hp:500,maxHp:500,cooldown:0}];applyCommand(s,hero.id,{type:'ability',slot:1,x:10,y:20});assert.ok(hero.x<7.3);});
test('sprint matches shared movement speed and expires after three seconds',()=>{const {s,hero}=arena();s.actors=[hero];applyCommand(s,hero.id,{type:'ability',slot:2});assert.equal(getMoveSpeed(hero,0),7.5);applyCommand(s,hero.id,{type:'steer',x:0,y:1});stepGame(s,.1);assert.ok(Math.abs(hero.y-20.75)<1e-6);assert.equal(getMoveSpeed(hero,2.999),7.5);assert.equal(getMoveSpeed(hero,3),5);assert.equal(hero.abilityCooldowns?.[1],11.9);});
test('shockwave deals fixed damage, pushes units and respects blocked destinations',()=>{const {s,hero,enemy}=arena();enemy.x=7;enemy.y=20;s.structures=[{id:'block',kind:'tower',team:'red',x:8.1,y:20,hp:500,maxHp:500,cooldown:0}];applyCommand(s,hero.id,{type:'ability',slot:3});assert.equal(enemy.hp,enemy.maxHp-SHOCKWAVE_DAMAGE);assert.ok(enemy.x>7&&enemy.x<7.4);assert.ok(canOccupy(s,enemy,enemy.id));assert.equal(s.structures[0].x,8.1);});
test('all selectable heroes share the same three skill rules',()=>{for(const kind of ['knight','ranger','lancer'] as const){const {s,hero}=arena();hero.hero=kind;s.actors=[hero];for(const slot of [1,2,3] as const)assert.equal(applyCommand(s,hero.id,{type:'ability',slot,x:6,y:25}).ok,true);assert.deepEqual(hero.abilityCooldowns,[8,12,16]);assert.equal(hero.sprintUntil,3);}});
