const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const ROOT='/assets/tiny-swords/';
const files={grass:'Terrain/Tileset/Tilemap_color2.png',deepgrass:'Terrain/Tileset/Tilemap_color3.png',idle:'Units/Blue Units/Warrior/Warrior_Idle.png',run:'Units/Blue Units/Warrior/Warrior_Run.png',attack:'Units/Blue Units/Warrior/Warrior_Attack1.png',sheep:'Terrain/Resources/Meat/Sheep/Sheep_Idle.png',rock:'Terrain/Decorations/Rocks/Rock1.png'};
for(let i=1;i<=4;i++){files['tree'+i]=`Terrain/Resources/Wood/Trees/Tree${i}.png`;files['bush'+i]=`Terrain/Decorations/Bushes/Bushe${i}.png`;}
for(const b of ['House1','House2','House3','Castle','Tower','Monastery'])files[b]=`Buildings/Blue Buildings/${b}.png`;
const imgs={};
const W=3200,H=2560,T=64,COLS=W/T,ROWS=H/T;
let seed=1873;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const land=[];
function river(y){return 2230+Math.sin(y/310)*100;}
for(let y=0;y<ROWS;y++){land[y]=[];for(let x=0;x<COLS;x++){const px=x*T+32,py=y*T+32;const edge=Math.pow((px-1600)/1510,4)+Math.pow((py-1280)/1160,4);land[y][x]=edge<.92+Math.sin(y*.9)*.05&&Math.abs(px-river(py))>84;}}
function ground(x,y){return !!land[Math.floor(y/T)]?.[Math.floor(x/T)];}
const bridges=[{x:2205,y:1184,w:300,h:88},{x:2190,y:576,w:300,h:88},{x:2070,y:1920,w:300,h:88}];
const paths=[[[490,1850],[650,1550],[980,1250],[1220,1180],[1660,1220],[2050,1230],[2510,1230],[2750,1440]],[[1220,1180],[1210,830],[1450,600],[1820,620],[2430,620],[2720,520]],[[1660,1220],[1740,1570],[1870,1960],[2410,1960],[2660,1810]],[[980,1250],[850,920],[560,640]],[[1210,830],[1060,760]],[[1450,600],[1460,420]]];
function distSegment(x,y,a,b){const dx=b[0]-a[0],dy=b[1]-a[1],t=clamp(((x-a[0])*dx+(y-a[1])*dy)/(dx*dx+dy*dy),0,1);return Math.hypot(x-a[0]-t*dx,y-a[1]-t*dy);}
function pathDist(x,y){let d=1e9;for(const p of paths)for(let i=1;i<p.length;i++)d=Math.min(d,distSegment(x,y,p[i-1],p[i]));return d;}
const objects=[];function obj(type,x,y,scale=1){const o={type,x,y,scale,phase:rand()*8};objects.push(o);return o;}
obj('Castle',1470,500,1.05);obj('House1',1060,790);obj('House2',1300,1040);obj('House3',1550,1010);obj('House1',960,1160);obj('House2',1760,1180);obj('Monastery',2720,540);obj('Tower',610,640);obj('House3',2540,1730);
for(let i=0;i<470;i++){let x=170+rand()*2860,y=200+rand()*2180;if(!ground(x,y)||!ground(x-55,y)||!ground(x+55,y)||pathDist(x,y)<105||objects.some(o=>Math.hypot(x-o.x,y-o.y)<145))continue;obj('tree'+(1+Math.floor(rand()*4)),x,y,.78+rand()*.3);}
for(let i=0;i<380;i++){let x=160+rand()*2880,y=180+rand()*2200;if(!ground(x,y)||pathDist(x,y)<65||objects.some(o=>Math.hypot(x-o.x,y-o.y)<60))continue;obj(rand()<.75?'bush'+(1+Math.floor(rand()*4)):'rock',x,y,.65+rand()*.35);}
for(const [x,y]of [[1110,1410],[1210,1480],[1300,1380],[1040,1530],[1430,1530],[2630,1330]])obj('sheep',x,y,.85);
const places=[{name:'Willowbrook',x:1300,y:1190,r:430,desc:'Blue roofs. Open doors. A place to call home.'},{name:'Whispering Woods',x:590,y:690,r:330,desc:'Where the trees have stories of their own.'},{name:'Sunlit Meadow',x:620,y:1820,r:360,desc:'Nothing to do. Nowhere else to be.'},{name:'The Old Abbey',x:2700,y:620,r:320,desc:'A quiet keeper of forgotten stories.'},{name:'Fernwater Crossing',x:2510,y:1850,r:350,desc:'Follow the river a little further.'}];
let visited=new Set([0]),current=0;
const player={x:1320,y:1240,face:1,moving:false,attack:0};const camera={x:player.x,y:player.y};const keys=new Set();let time=0,last=0,viewW=0,viewH=0,zoom=1.1,ready=false;
const terrain=document.createElement('canvas');terrain.width=W;terrain.height=H;const g=terrain.getContext('2d');g.imageSmoothingEnabled=false;
function tile(sx,sy,x,y,img=imgs.grass){g.drawImage(img,sx*64,sy*64,64,64,x,y,64,64);}
function bake(){
 g.fillStyle='#4b99ad';g.fillRect(0,0,W,H);
 for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++)if(land[y][x]){const n=land[y-1]?.[x],s=land[y+1]?.[x],w=land[y][x-1],e=land[y][x+1];let tx=!w?0:!e?2:1,ty=!n?0:!s?2:1;tile(tx,ty,x*T,y*T,x<14?imgs.deepgrass:imgs.grass);}
 // Soft, well-trodden paths are clipped to dry land.
 g.save();g.beginPath();for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++)if(land[y][x])g.rect(x*T,y*T,T,T);g.clip();
 for(const [width,color]of [[86,'#aeb76e'],[74,'#c4be82'],[61,'#d3c68f']]){g.strokeStyle=color;g.lineWidth=width;g.lineJoin='round';g.lineCap='round';for(const p of paths){g.beginPath();p.forEach(([x,y],i)=>i?g.lineTo(x,y):g.moveTo(x,y));g.stroke();}}
 for(let i=0;i<22000;i++){const x=rand()*W,y=rand()*H,d=pathDist(x,y);if(d<29){g.fillStyle=rand()<.5?'#bbae7960':'#eee0a770';g.fillRect(x,y,2+rand()*4,2);}else if(d>55){g.fillStyle=['#e2dc9155','#43895650','#b6cf6c80'][Math.floor(rand()*3)];g.fillRect(x,y,2,3);if(rand()<.25)g.fillRect(x+3,y-2,2,4);}}
 // Wildflower patches, deliberately grouped around clearings.
 for(let i=0;i<1300;i++){const x=rand()*W,y=rand()*H;if(pathDist(x,y)<65||Math.sin(x/120)+Math.cos(y/140)<.8)continue;g.fillStyle='#45875a';g.fillRect(x,y,2,6);g.fillStyle=['#faf0b4','#f3d17e','#e9b3a2','#d7e1ee'][i%4];g.fillRect(x-2,y-2,5,3);g.fillRect(x,y-4,2,6);}
 g.restore();
 for(const b of bridges){g.fillStyle='#315962';g.fillRect(b.x-4,b.y+7,b.w+8,b.h);g.fillStyle='#836a4d';g.fillRect(b.x,b.y,b.w,b.h);for(let x=b.x+2;x<b.x+b.w;x+=14){g.fillStyle='#be9c69';g.fillRect(x,b.y+3,11,b.h-6);g.fillStyle='#d9b87d';g.fillRect(x,b.y+3,3,b.h-6);}for(const y of [b.y-8,b.y+b.h-9]){g.fillStyle='#65533d';g.fillRect(b.x-8,y+6,b.w+16,6);g.fillStyle='#d8b77a';g.fillRect(b.x-8,y,b.w+16,6);for(let x=b.x;x<=b.x+b.w;x+=55){g.fillStyle='#69543f';g.fillRect(x,y-9,8,22);g.fillStyle='#efd09a';g.fillRect(x-1,y-10,10,5);}}}
 // A village garden and a stone meeting circle.
 g.strokeStyle='#a6ae78';g.lineWidth=8;g.beginPath();g.ellipse(1318,1238,86,45,0,0,Math.PI*2);g.stroke();
 for(let i=0;i<14;i++){const a=i/14*Math.PI*2;g.fillStyle='#dde0ac';g.fillRect(1318+Math.cos(a)*86-6,1238+Math.sin(a)*45-4,12,8);}
 for(let r=0;r<4;r++)for(let c=0;c<7;c++){const x=1470+c*20,y=1110+r*18;g.fillStyle='#967b50';g.fillRect(x,y,17,14);g.fillStyle='#427e50';g.fillRect(x+6,y+2,5,9);g.fillStyle=r%2?'#eac473':'#9ec35e';g.fillRect(x+3,y+2,10,4);}
}
function resize(){const dpr=Math.min(devicePixelRatio,2);viewW=innerWidth;viewH=innerHeight;canvas.width=viewW*dpr;canvas.height=viewH*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.imageSmoothingEnabled=false;zoom=viewW<700?.85:1.1;}
function walkable(x,y){if(x<64||y<64||x>W-64||y>H-64)return false;const bridge=bridges.some(b=>x>b.x-15&&x<b.x+b.w+15&&y>b.y+12&&y<b.y+b.h-14);if(!bridge&&(!ground(x-12,y-4)||!ground(x+12,y+5)))return false;for(const o of objects){if(o.type.startsWith('tree')){if(Math.hypot(x-o.x,y-o.y)<21*o.scale)return false;}else if(/House|Castle|Tower|Monastery/.test(o.type)){const half=(o.type==='Castle'?114:o.type==='Monastery'?60:40)*o.scale;if(Math.abs(x-o.x)<half+10&&y>o.y-55*o.scale&&y<o.y+6)return false;}}return true;}
function sprite(o){const im=imgs[o.type];let sw=im.width,sh=im.height,f=0;if(o.type.startsWith('tree')||o.type.startsWith('bush')){sw=im.width/8;f=Math.floor(time*6+o.phase)%8;}if(o.type==='sheep'){sw=128;f=Math.floor(time*5+o.phase)%6;}const w=sw*o.scale,h=sh*o.scale;ctx.drawImage(im,f*sw,0,sw,sh,Math.round(o.x-w/2),Math.round(o.y-h+(o.type.startsWith('tree')?20:o.type==='sheep'?32:/House|Castle|Tower|Monastery/.test(o.type)?20:20)*o.scale),w,h);}
function drawKnight(){let type=player.attack>0?'attack':player.moving?'run':'idle',count=type==='attack'?4:type==='run'?6:8,f=type==='attack'?Math.min(3,Math.floor((.4-player.attack)*10)):Math.floor(time*(player.moving?11:7))%count;ctx.save();ctx.translate(Math.round(player.x),Math.round(player.y));ctx.scale(player.face,1);ctx.drawImage(imgs[type],f*192,0,192,192,-76.8,-109,153.6,153.6);ctx.restore();ctx.fillStyle='#f8e8aa';ctx.beginPath();ctx.moveTo(player.x,player.y-86+Math.sin(time*3)*3);ctx.lineTo(player.x-4,player.y-92+Math.sin(time*3)*3);ctx.lineTo(player.x+4,player.y-92+Math.sin(time*3)*3);ctx.fill();}
let toastTimer;function toast(title,body){const el=document.querySelector('#toast');el.querySelector('small').textContent=title;el.querySelector('span').textContent=body;el.classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.add('hidden'),5000);}
function update(dt){if(document.querySelector('dialog[open]')){player.moving=false;return;}let dx=Number(keys.has('d')||keys.has('arrowright'))-Number(keys.has('a')||keys.has('arrowleft')),dy=Number(keys.has('s')||keys.has('arrowdown'))-Number(keys.has('w')||keys.has('arrowup'));player.moving=!!(dx||dy);if(dx)player.face=dx;const length=Math.hypot(dx,dy)||1,speed=keys.has('shift')?265:170;dx=dx/length*dt*speed;dy=dy/length*dt*speed; // axis-separated collision allows sliding along obstacles
 if(walkable(player.x+dx,player.y))player.x+=dx;if(walkable(player.x,player.y+dy))player.y+=dy;player.attack=Math.max(0,player.attack-dt);
 const nearest=places.reduce((best,p,i)=>Math.hypot(p.x-player.x,p.y-player.y)<Math.hypot(places[best].x-player.x,places[best].y-player.y)?i:best,0);if(nearest!==current){current=nearest;document.querySelector('#location').textContent=places[current].name;}
 if(!visited.has(nearest)&&Math.hypot(player.x-places[nearest].x,player.y-places[nearest].y)<places[nearest].r){visited.add(nearest);document.querySelector('#discovered').textContent=`${visited.size} / 5`;document.querySelector('#progress').style.width=visited.size*20+'%';document.querySelector('#map-count').textContent=`${visited.size} of 5 places discovered`;toast(visited.size===5?'THE REALM, A LITTLE MORE FAMILIAR':'NEW PLACE DISCOVERED',visited.size===5?'Five places. A thousand little stories.':places[nearest].name+' — '+places[nearest].desc);}
}
function drawMap(target,big=false){const c=target.getContext('2d'),w=target.width,h=target.height,sx=w/W,sy=h/H;c.fillStyle='#397383';c.fillRect(0,0,w,h);c.fillStyle='#8fba77';for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++)if(land[y][x])c.fillRect(x*T*sx,y*T*sy,T*sx+1,T*sy+1);c.strokeStyle='#dbca91';c.lineWidth=big?4:2;for(const path of paths){c.beginPath();path.forEach(([x,y],i)=>i?c.lineTo(x*sx,y*sy):c.moveTo(x*sx,y*sy));c.stroke();}for(const o of objects){if(o.type.startsWith('tree')){c.fillStyle='#477d57';c.fillRect(o.x*sx-1,o.y*sy-2,big?5:2,big?6:3);}else if(/House|Castle|Tower|Monastery/.test(o.type)){c.fillStyle='#446e87';c.fillRect(o.x*sx-2,o.y*sy-3,big?9:4,big?8:4);}}
 if(big){places.forEach((p,i)=>{c.fillStyle=visited.has(i)?'#fff0bc':'#d5e4c5';c.font='600 15px Georgia';c.textAlign='center';c.shadowColor='#264f37';c.shadowBlur=4;c.fillText(visited.has(i)?p.name:'?  Undiscovered',p.x*sx,p.y*sy+29);c.shadowBlur=0;});}else{c.strokeStyle='#fff9d66b';c.lineWidth=1;c.strokeRect((camera.x-viewW/zoom/2)*sx,(camera.y-viewH/zoom/2)*sy,viewW/zoom*sx,viewH/zoom*sy);}
 c.fillStyle='#233e35';c.beginPath();c.arc(player.x*sx,player.y*sy,big?8:5,0,Math.PI*2);c.fill();c.fillStyle='#fff4b9';c.beginPath();c.arc(player.x*sx,player.y*sy,big?5:3,0,Math.PI*2);c.fill();}
function frame(ms){const dt=Math.min((ms-last)/1000||0,.035);last=ms;time+=dt;if(ready){update(dt);const ease=1-Math.exp(-dt*7);camera.x+=(player.x-camera.x)*ease;camera.y+=(player.y-camera.y)*ease;const hw=viewW/zoom/2,hh=viewH/zoom/2;camera.x=clamp(camera.x,hw,W-hw);camera.y=clamp(camera.y,hh,H-hh);ctx.clearRect(0,0,viewW,viewH);ctx.save();ctx.translate(viewW/2,viewH/2);ctx.scale(zoom,zoom);ctx.translate(-Math.round(camera.x),-Math.round(camera.y));ctx.drawImage(terrain,0,0);
 // Sunlight ripples over the river and the sea.
 ctx.strokeStyle='#b6e5d540';ctx.lineWidth=2;for(let i=0;i<160;i++){let x=(i*277)%W,y=(i*193)%H;if(ground(x,y))continue;ctx.globalAlpha=.35+Math.sin(time*2+i)*.25;ctx.beginPath();ctx.moveTo(x+Math.sin(time+i)*5,y);ctx.lineTo(x+15+Math.sin(time+i)*5,y);ctx.stroke();}ctx.globalAlpha=1;
 const visible=objects.filter(o=>Math.abs(o.x-camera.x)<hw+200&&Math.abs(o.y-camera.y)<hh+280);visible.push({type:'player',x:player.x,y:player.y});visible.sort((a,b)=>a.y-b.y);for(const o of visible)o.type==='player'?drawKnight():sprite(o);
 // Small drifting pollen motes and butterflies.
 for(let i=0;i<38;i++){const x=(i*173+Math.sin(time*.3+i)*30)%W,y=(i*137+time*5)%H;if(!ground(x,y))continue;ctx.fillStyle=i%3?'#fff0b9a0':'#fcdbc8';let flutter=Math.sin(time*9+i)*3;ctx.fillRect(x,y,2+Math.abs(flutter),2);if(i%3===0)ctx.fillRect(x+4,y+flutter,3,2);}
 ctx.restore();const vignette=ctx.createRadialGradient(viewW*.5,viewH*.45,viewH*.23,viewW*.5,viewH*.5,viewW*.7);vignette.addColorStop(0,'#163d2a00');vignette.addColorStop(1,'#163d2a38');ctx.fillStyle=vignette;ctx.fillRect(0,0,viewW,viewH);drawMap(document.querySelector('#minimap'));if(document.querySelector('#map-dialog').open)drawMap(document.querySelector('#bigmap'),true);}
 requestAnimationFrame(frame);}
function openMap(){const d=document.querySelector('#map-dialog');if(d.open)d.close();else{keys.clear();drawMap(document.querySelector('#bigmap'),true);d.showModal();}}
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' ','m','shift'].includes(k))e.preventDefault();if(k==='m'&&!e.repeat&&!document.querySelector('#help-dialog').open)openMap();if(k===' '&&!e.repeat&&!document.querySelector('dialog[open]'))player.attack=.4;keys.add(k);});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>keys.clear());
document.querySelector('#map-button').onclick=openMap;document.querySelector('#help').onclick=()=>{keys.clear();document.querySelector('#help-dialog').showModal();};document.querySelectorAll('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelector('#start').onclick=()=>document.querySelector('#help-dialog').close();document.querySelectorAll('dialog').forEach(d=>d.addEventListener('close',()=>{keys.clear();canvas.focus({preventScroll:true});}));
for(const b of document.querySelectorAll('[data-key]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key);});for(const evt of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(evt,()=>keys.delete(b.dataset.key));}
let audioCtx,audioGain;document.querySelector('#sound').onclick=async()=>{if(!audioCtx){audioCtx=new AudioContext();audioGain=audioCtx.createGain();audioGain.gain.value=.035;audioGain.connect(audioCtx.destination);const buffer=audioCtx.createBuffer(1,audioCtx.sampleRate*3,audioCtx.sampleRate),data=buffer.getChannelData(0);let prev=0;for(let i=0;i<data.length;i++){prev=(prev+Math.random()*.04-.02)/1.02;data[i]=prev*4;}const source=audioCtx.createBufferSource();source.buffer=buffer;source.loop=true;const filter=audioCtx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=650;source.connect(filter);filter.connect(audioGain);source.start();}else if(audioCtx.state==='running')await audioCtx.suspend();else await audioCtx.resume();const enabled=audioCtx.state==='running';document.querySelector('#sound').classList.toggle('on',enabled);document.querySelector('#sound').setAttribute('aria-label',enabled?'Mute nature sounds':'Enable nature sounds');};
addEventListener('resize',resize);resize();requestAnimationFrame(frame);
try{await Promise.all(Object.entries(files).map(([k,path])=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{imgs[k]=im;resolve();};im.onerror=()=>reject(new Error('Could not load '+path));im.src=ROOT+path;})));bake();ready=true;document.querySelector('#loading').style.opacity=0;setTimeout(()=>document.querySelector('#loading').remove(),550);toast('WELCOME, WANDERER','Your story starts with a single step.');canvas.focus({preventScroll:true});}catch(e){document.querySelector('#loading p').textContent='The world couldn’t load. Please refresh to try again.';console.error(e);}
// Read-only diagnostics for verifying movement and world connectivity.
window.realm={get state(){return {ready,x:player.x,y:player.y,visited:[...visited],location:places[current].name};},walkable,places,world:{width:W,height:H}};
