export function createUI({ client, onViewChange = () => {} }) {
  const root = document.querySelector('#ui');
  const view = { tactical: false, inspect: null, grid: false, buildMode: false, inputDisabled: true, aim: null };
  let currentSession, hero, joining = false, resultShown = false, lastError = '', latestAction = '', stick = { x: 0, y: 0, active: false };
  const listeners = [];
  const listen = (el, type, fn, opts) => { el.addEventListener(type, fn, opts); listeners.push(() => el.removeEventListener(type, fn, opts)); };
  const heroes = [['knight','Knight','Close combat · frontline'],['ranger','Ranger','Ranged · precision'],['lancer','Lancer','Reach · sweeping strikes']];
  const icons = {attack:'<path d="m8 26 18-18 6-2-2 6-18 18M6 22l12 12M5 35l7-7"/>',ability1:'<path d="m8 29 20-20M16 7h17v17M6 18l9 9M10 34l7-7"/>',ability2:'<path d="m21 4 13 5v10c0 9-13 17-13 17S8 28 8 19V9Z"/><path d="m15 20 5 5 8-11"/>',ability3:'<path d="m23 3-15 21h12l-2 13 15-22H21Z"/>',recall:'<path d="M10 15a13 13 0 1 1-2 14M4 8v10h10M17 26V16l5-5 5 5v10Z"/>',regen:'<path d="M17 6h8v11h11v8H25v11h-8V25H6v-8h11Z"/>',gather:'<path d="m10 35 17-27M14 7c9-4 17 0 21 8l-9 5-5-8M6 29l8 5"/>',build:'<path d="M9 36V16H6V5h7v6h5V5h7v6h5V5h6v11h-3v20ZM18 36V25h7v11"/>'};
  const icon=name=>`<svg viewBox="0 0 42 42" fill="none" stroke="currentColor" stroke-width="2.3" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.attack}</svg>`;
  const companions = [['guardian','Guardian','Protect your hero'],['scout','Scout','Fast escort'],['harvester','Harvester','Gather resources']];
  const choices = (items, name) => `<div class="choices" data-choice="${name}">${items.map(([v,n,d],i)=>`<button type="button" data-value="${v}" aria-pressed="${i===0}" class="${i===0?'selected':''}"><span class="draft-sprite sprite-${v}" aria-hidden="true"></span><b>${n}</b><small>${d}</small></button>`).join('')}</div>`;
  root.innerHTML = `<header class="topbar"><div class="wordmark"><span class="crest">♜</span>LITTLE REALM<small>THE DIVIDED REALM</small></div><div class="bank"><span class="blue">◆ <b id="blue-core">—</b></span><span id="clock">00:00</span><span class="red">◆ <b id="red-core">—</b></span><span>Wood <b id="wood">0</b></span><span>Gold <b id="gold">0</b></span></div><div class="utility"><button id="grid-toggle" title="Tile grid" aria-label="Toggle tile grid">▦</button><button id="fullscreen" title="Fullscreen" aria-label="Fullscreen">⛶</button><button id="help" title="Controls and match options" aria-label="Controls and match options">?</button></div></header>
  <div class="hud"><div class="room-strip"><span class="status-dot"></span><span id="connection">Connecting</span> · <button id="copy-room" title="Copy duel invite link">Room <b id="room-code">—</b></button></div><div id="tactical-hint" class="tactical-hint" hidden>Realm overview · select a destination to move · M to return</div><section class="hero-panel"><div class="hero-title"><b id="hero-name">Your knight</b><small id="hero-class">Knight</small></div><div class="health" role="meter" aria-label="Hero health" aria-valuemin="0" aria-valuemax="100"><i id="hp-bar"></i></div><div class="hero-meta"><span id="hp-value">— HP</span><span id="kills">0 defeats</span></div></section><section class="companion"><div class="orders" id="orders" hidden>${['gather','escort','attack','defend'].map(o=>`<button data-order="${o}">${o[0].toUpperCase()+o.slice(1)}</button>`).join('')}</div><button class="companion-toggle" id="companion-toggle" aria-expanded="false"><span id="companion-name">Your companion</span> <span aria-hidden="true">⌃</span><small id="companion-state">Choose an order</small></button></section><div class="joystick" id="joystick" role="group" aria-label="Touch movement joystick"><i></i></div><div class="actions">${[['attack','⚔','Attack','Space'],['gather','♧','Gather','E'],['ability','✧','Ability','Q'],['build','♜','Tower','B'],['recall','⌂','Recall','R'],['map','◇','Map','M']].map(([a,icon,label,key])=>`<button data-action="${a}" title="${label}${a==='build'?' · select a nearby tile':''}"><kbd>${key}</kbd><strong aria-hidden="true">${icon}</strong><span>${label}</span></button>`).join('')}</div><button class="map-panel" id="map-button" aria-label="Toggle realm overview"><canvas id="minimap" width="180" height="180"></canvas><span>THE REALM <b>↗</b></span></button><div class="message" id="message" role="status" hidden></div></div>
  <section class="join-screen" id="join-screen"><form id="draft"><div class="join-heading"><div class="wordmark"><span class="crest">♜</span>LITTLE REALM</div><h1>One lane.<br>One rival.</h1><p class="intro">Bring a friend. Choose your hero and companion.<br>Break the enemy core.</p></div><label>Your name<input name="name" placeholder="Enter your name" maxlength="18" autocomplete="nickname" value="Wanderer"></label><div><span class="legend">Choose your hero</span>${choices(heroes,'hero')}</div><div><span class="legend">Choose your companion</span>${choices(companions,'companion')}</div><label>Room code <small>optional</small><input name="room" placeholder="Enter your friend's code" maxlength="12" autocomplete="off" spellcheck="false" autocapitalize="characters"></label><div><button id="join" class="primary" type="submit">Create duel</button><p id="join-error" class="join-error" role="alert"></p><div class="join-footer"><span>Copy your invite in the match.<br>A bot plays until your friend joins.</span><span>1 hero + 1 companion<br>on each side</span></div></div></form><div class="join-note">1v1 DUEL<small>One companion each</small></div></section>
  <dialog id="help-dialog"><button class="close" aria-label="Close controls">×</button><h2>Make your move.</h2><p>Gather wood and gold, build towers near your hero, then destroy the enemy core. Companions follow the order you choose. The match keeps running while this is open.</p><ul><li><span>Move / choose destination</span><b>WASD / click map</b></li><li><span>Attack / gather</span><b>Space / E</b></li><li><span>Hero ability / recall</span><b>Q / R</b></li><li><span>Build / overview</span><b>B / M</b></li><li><span>Cancel / close</span><b>Esc</b></li></ul><p>On phones, use the left joystick and right action buttons. Tap Tower, then an empty nearby tile. Teammates share resources.</p><div class="dialog-actions"><button id="leave">Leave match</button><button class="primary" id="resume">Return to match</button></div></dialog><dialog id="results"><h2 id="result-title">The realm is yours.</h2><p id="result-body"></p><div class="dialog-actions"><button id="result-leave">Leave match</button><button class="primary" id="restart">Play again</button></div></dialog>`;
  document.body.classList.add('join-active');
  const $ = s => root.querySelector(s);
  const roomInput=$('input[name="room"]');
  roomInput.value=(new URLSearchParams(location.search).get('room')||'').replace(/[^a-z0-9]/gi,'').slice(0,12).toUpperCase();
  const updateJoinLabel=()=>{if(!joining)$('#join').textContent=roomInput.value.trim()?'Join duel':'Create duel';};
  listen(roomInput,'input',updateJoinLabel);
  updateJoinLabel();
  let loadState={phase:'critical',completed:0,total:0,playable:false};
  const loadPanel=document.querySelector('#loading');
  if(loadPanel)$('#join').before(loadPanel);
  const setLoadState=next=>{
    loadState={...loadState,...next};
    if(!loadPanel)return;
    const {phase,completed,total,playable,error}=loadState;
    const failed=Boolean(error&&!playable),complete=playable&&completed>=total;
    loadPanel.dataset.failed=String(failed);loadPanel.dataset.complete=String(complete);
    const progress=loadPanel.querySelector('progress');
    if(total>0){progress.max=total;progress.value=Math.min(completed,total);}else progress.removeAttribute('value');
    loadPanel.querySelector('#load-count').textContent=total>0?`${completed} / ${total}`:'';
    loadPanel.querySelector('#load-title').textContent=failed?'Artwork could not load':playable?(complete?'Ready to play':'Finishing scenery'):'Preparing your battlefield';
    progress.setAttribute('aria-label',playable?'Background artwork loading':'Essential artwork loading');
    loadPanel.querySelector('#load-detail').textContent=failed?'Check your connection and retry. You have not entered a match.':playable?(error?'Some scenery is unavailable. You can still play.':complete?'Choose your hero and enter the realm.':'You can play now. Extra scenery is loading in the background.'):joining?'Your selection is saved. Joining as soon as the battlefield is ready.':'Choose your hero while the essential artwork loads.';
    loadPanel.querySelector('#load-retry').hidden=!failed;
    if(joining)$('#join').textContent=failed?'Loading failed':playable?'Connecting to match…':'Preparing battlefield…';
  };
  $('.topbar .wordmark').remove();
  $('.bank').innerHTML='<span class="blue"><b id="blue-score">0</b><small id="blue-core">100%</small></span><span id="clock">00:00</span><span class="red"><b id="red-score">0</b><small id="red-core">100%</small></span>';
  $('.hud').insertAdjacentHTML('beforeend','<div class="resource-bank"><span>Wood <b id="wood">0</b></span><span>Gold <b id="gold">0</b></span></div><div id="aim-cancel" class="aim-cancel" hidden>×<small>Cancel</small></div>');
  $('.actions').outerHTML=`<div class="combat-controls"><button data-action="attack" class="combat-button attack" aria-label="Attack: hold Space or hold this button" title="Hold Space to attack. Release to stop."><kbd>Space</kbd>${icon('attack')}<span>Attack</span></button>${[1,2,3].map((slot,i)=>`<button data-action="ability" data-slot="${slot}" class="combat-button skill skill-${slot}" aria-label="Ability ${slot}"><kbd>${['Q','E','F'][i]}</kbd>${icon(`ability${slot}`)}<span class="skill-name">Skill ${slot}</span><b class="cooldown" hidden></b></button>`).join('')}</div><div class="utility-actions">${[['recall','Recall','R'],['regen','Regen','T']].map(([a,n,k])=>`<button data-action="${a}" class="combat-button"><kbd>${k}</kbd>${icon(a)}<span>${n}</span><b class="cooldown" hidden></b></button>`).join('')}</div><div class="economy-actions">${[['gather','Gather','C'],['build','Build','B']].map(([a,n,k])=>`<button data-action="${a}"><kbd>${k}</kbd>${icon(a)}<span>${n}</span></button>`).join('')}</div>`;
  $('#help-dialog ul').innerHTML='<li><span>Move / hold to attack</span><b>WASD / Space</b></li><li><span>Skills 1 / 2 / 3</span><b>Q / E / F</b></li><li><span>Recall / regenerate</span><b>R / T</b></li><li><span>Gather / build</span><b>C / B</b></li><li><span>Overview / grid</span><b>M / G</b></li>';
  $('#help-dialog').querySelectorAll('p')[1].textContent='Hold the left joystick to move and the large Attack button to strike nearby enemies. Drag Dash to aim and release to strike through enemies. Tap Sprint for 3 seconds of speed; tap Shockwave to damage and push nearby enemies away. Drag to × to cancel a cast. Recall channels for 3 seconds; moving cancels it. Build and Gather are at the upper right. Your companion follows your orders. Push with your minions to bring down the enemy core.';
  const heroKit=[['Dash',3,'Dash through enemies for 180 damage. 8 second cooldown.'],['Sprint',0,'Move 50% faster for 3 seconds. 12 second cooldown.'],['Shockwave',3,'Deal 150 damage around you and push enemies back. 16 second cooldown.']];
  const skills={knight:heroKit,ranger:heroKit,lancer:heroKit};
  const kitIcons=[
    '<path d="m8 29 20-20M16 7h17v17M6 18l9 9M10 34l7-7"/>',
    '<path d="m20 8-4 11 7 5 4 10h9l-5-15-6-3 3-8M5 12h8M3 20h8M6 29h9"/>',
    '<circle cx="21" cy="21" r="5"/><circle cx="21" cy="21" r="12"/><path d="M21 2v4M21 36v4M2 21h4M36 21h4M7 7l3 3M32 32l3 3M7 35l3-3M32 10l3-3"/>'
  ];
  root.querySelectorAll('[data-slot]').forEach(b=>{b.querySelector('svg').innerHTML=kitIcons[Number(b.dataset.slot)-1];});
  $('.hud').insertAdjacentHTML('beforeend','<div id="cast-status" class="cast-status" role="status" hidden><strong></strong><span></span><div class="cast-meter"><i></i></div></div>');
  let messageTimer;
  const message = (text, error = false) => { clearTimeout(messageTimer); if (/^moving\b/i.test(text)) text=''; $('#message').textContent=text; $('#message').hidden=!text; $('#message').classList.toggle('error', error); if(text&&!view.buildMode)messageTimer=setTimeout(()=>{$('#message').hidden=true;},error?5000:2400); };
  const sync = () => { view.inputDisabled=!currentSession || $('#help-dialog').open || $('#results').open; $('[data-action="build"]').classList.toggle('active',view.buildMode); $('#map-button').classList.toggle('active',view.tactical||!!view.inspect); $('#map-button').setAttribute('aria-pressed',String(view.tactical)); $('#grid-toggle').classList.toggle('active',view.grid); $('#tactical-hint').hidden=!view.tactical; $('#tactical-hint').textContent='Realm overview · tap a region to inspect · M to return'; if($('#return-hero'))$('#return-hero').hidden=!(view.tactical||view.inspect); onViewChange({...view}); };
  const action = name => { if(!currentSession || view.inputDisabled) return; if(name==='map'){view.tactical=!(view.tactical||view.inspect);view.inspect=null;sync();} else if(name==='build'){view.buildMode=!view.buildMode;view.returnToHero?.();message(view.buildMode?'Build a tower · tap an empty tile near your hero. Esc to cancel.':'');sync();} else {view.buildMode=false;client.command({type:name});sync();} };
  root.querySelectorAll('[data-choice]').forEach(group => listen(group,'click',e=>{const b=e.target.closest('button');if(!b)return;group.querySelectorAll('button').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});}));
  listen($('#draft'),'submit',async e=>{e.preventDefault();if(joining)return;joining=true;$('#join').disabled=true;setLoadState({});$('#join-error').textContent='';const data=new FormData(e.currentTarget);try{await client.join({name:String(data.get('name')).trim()||'Wanderer',size:1,room:String(data.get('room')).trim().toUpperCase()||undefined,hero:$('[data-choice="hero"] .selected').dataset.value,companion:$('[data-choice="companion"] .selected').dataset.value});}catch(err){$('#join-error').textContent=err?.message||'Could not connect. Please try again.';joining=false;$('#join').disabled=false;$('#join').textContent=(roomInput.value.trim()?'Join duel':'Create duel');}});
  root.querySelectorAll('[data-action]:not([data-action="attack"]):not([data-action="ability"])').forEach(b=>listen(b,'click',()=>action(b.dataset.action)));
  root.querySelectorAll('[data-order]').forEach(b=>listen(b,'click',()=>{client.command({type:'order',order:b.dataset.order});$('#orders').hidden=true;$('#companion-toggle').setAttribute('aria-expanded','false');}));
  listen($('#companion-toggle'),'click',()=>{$('#orders').hidden=!$('#orders').hidden;$('#companion-toggle').setAttribute('aria-expanded',String(!$('#orders').hidden));});
  // A minimap gesture only inspects the camera; it must never issue a move.
  const mapButton=$('#map-button');let mapPointer=null,mapDragged=false;
  $('.hero-panel').insertAdjacentHTML('beforeend','<small id="combat-feedback" class="combat-feedback" role="status" hidden></small>');
  mapButton.insertAdjacentHTML('afterend','<button id="return-hero" class="return-hero" hidden>Return to hero</button>');
  view.returnToHero=()=>{view.inspect=null;view.tactical=false;sync();};
  const inspectMap=e=>{const r=$('#minimap').getBoundingClientRect();view.tactical=false;view.inspect={x:Math.max(0,Math.min(4096,(e.clientX-r.left)/r.width*4096)),y:Math.max(0,Math.min(4096,(e.clientY-r.top)/r.height*4096))};sync();};
  listen(mapButton,'pointerdown',e=>{if(view.inputDisabled)return;e.preventDefault();mapPointer={id:e.pointerId,x:e.clientX,y:e.clientY};mapDragged=false;mapButton.setPointerCapture(e.pointerId);});
  listen(mapButton,'pointermove',e=>{if(mapPointer?.id!==e.pointerId)return;if(Math.hypot(e.clientX-mapPointer.x,e.clientY-mapPointer.y)>5)mapDragged=true;if(mapDragged)inspectMap(e);});
  listen(mapButton,'pointerup',e=>{if(mapPointer?.id!==e.pointerId)return;if(mapDragged)inspectMap(e);else action('map');mapPointer=null;});
  listen(mapButton,'pointercancel',()=>{mapPointer=null;});
  // Keyboard activation has no pointer sequence. Pointer clicks are already handled above.
  listen(mapButton,'click',e=>{if(e.detail===0)action('map');});
  listen($('#return-hero'),'click',()=>view.returnToHero());
  listen($('#grid-toggle'),'click',()=>{view.grid=!view.grid;sync();});
  listen($('#fullscreen'),'click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else message('Fullscreen is unavailable here. Add to your home screen for a standalone view.');}catch{message('Fullscreen is unavailable in this browser.');}});
  listen($('#copy-room'),'click',async()=>{try{const invite=new URL(location.href);invite.searchParams.set('room',currentSession?.room||'');await navigator.clipboard.writeText(invite.href);message('Invite link copied. Your friend will join the opposite side.');}catch{message(`Share room code: ${currentSession?.room||''}`);}});
  const closeHelp=()=>{$('#help-dialog').close();sync();};listen($('#help'),'click',()=>{$('#help-dialog').showModal();sync();});listen($('#help-dialog .close'),'click',closeHelp);listen($('#resume'),'click',closeHelp);listen($('#help-dialog'),'close',sync);
  const leave=()=>{client.disconnect();currentSession=null;$('#help-dialog').close();$('#results').close();$('#join-screen').hidden=false;document.body.classList.add('join-active');joining=false;$('#join').disabled=false;$('#join').textContent=(roomInput.value.trim()?'Join duel':'Create duel');view.tactical=false;view.buildMode=false;sync();};
  listen($('#leave'),'click',leave);listen($('#result-leave'),'click',leave);listen($('#restart'),'click',()=>{client.restart();$('#results').close();sync();});
  listen(window,'keydown',e=>{if(e.target.matches('input,select,textarea'))return;if(e.key==='Escape'){view.buildMode=false;view.tactical=false;view.inspect=null;$('#orders').hidden=true;closeHelp();sync();message('');return;}if(e.repeat)return;if(e.key.toLowerCase()==='g'){view.grid=!view.grid;sync();return;}const key={b:'build',m:'map'}[e.key.toLowerCase()];if(key){e.preventDefault();action(key);}});
  const pad=$('#joystick'),nub=pad.querySelector('i');let stickPointer=null,attackPointer=null,aimPointer=null,aimButton=null,lastSteerAt=-Infinity;
  const sendSteer=()=>{const now=performance.now();if(now-lastSteerAt<30)return;if(currentSession&&!view.inputDisabled){const length=Math.hypot(stick.x,stick.y),scale=length>0.999999?0.999999/length:1;client.command({type:'steer',x:stick.x*scale,y:stick.y*scale});lastSteerAt=now;}};
  const moveStick=e=>{const r=pad.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,l=Math.hypot(dx,dy),radius=r.width*.32,m=Math.min(1,radius/(l||1));stick.x=l<radius*.12?0:dx*m/radius;stick.y=l<radius*.12?0:dy*m/radius;nub.style.transform=`translate(${dx*m}px,${dy*m}px)`;sendSteer();};
  listen(pad,'pointerdown',e=>{if(view.inputDisabled||stickPointer!==null)return;e.preventDefault();pad.setPointerCapture(e.pointerId);stickPointer=e.pointerId;stick.active=true;moveStick(e);});listen(pad,'pointermove',e=>{if(e.pointerId===stickPointer)moveStick(e);});
  const stop=()=>{if(stick.active&&currentSession)client.command({type:'steer',x:0,y:0});lastSteerAt=-Infinity;stick={x:0,y:0,active:false};stickPointer=null;nub.style.transform='';};
  for(const event of ['pointerup','pointercancel','lostpointercapture'])listen(pad,event,e=>{if(e.pointerId===stickPointer)stop();});
  const attack=$('[data-action="attack"]');
  listen(window,'keydown',e=>{if(e.code==='Space'&&!/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)&&!e.target.isContentEditable&&!view.inputDisabled&&hero?.hp>0)attack.classList.add('active');});
  listen(window,'keyup',e=>{if(e.code==='Space'&&attackPointer===null)attack.classList.remove('active');});
  const stopAttack=()=>{if(attackPointer!==null&&currentSession)client.command({type:'attack',held:false});attackPointer=null;attack.classList.remove('active');};
  listen(attack,'pointerdown',e=>{if(view.inputDisabled||hero?.hp<=0||attackPointer!==null)return;e.preventDefault();attack.setPointerCapture(e.pointerId);attackPointer=e.pointerId;attack.classList.add('active');client.command({type:'attack',held:true});});
  for(const event of ['pointerup','pointercancel','lostpointercapture'])listen(attack,event,e=>{if(e.pointerId===attackPointer)stopAttack();});
  listen(attack,'click',e=>{if(e.detail===0&&!view.inputDisabled)client.command({type:'attack'});});
  const cancelAim=()=>{view.aim=null;aimPointer=null;aimButton?.classList.remove('active');aimButton=null;$('#aim-cancel').hidden=true;onViewChange({...view});};
  const moveAim=e=>{if(!aimButton||!hero)return;const r=aimButton.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,l=Math.hypot(dx,dy),slot=Number(aimButton.dataset.slot),range=skills[hero.hero]?.[slot-1]?.[1]??3,c=$('#aim-cancel').getBoundingClientRect();view.aim={slot,dx:l>8?dx/l:0,dy:l>8?dy/l:0,range,cancelled:e.clientX>=c.left-12&&e.clientX<=c.right+12&&e.clientY>=c.top-12&&e.clientY<=c.bottom+12};$('#aim-cancel').classList.toggle('active',view.aim.cancelled);onViewChange({...view});};
  root.querySelectorAll('[data-slot]').forEach(b=>{listen(b,'pointerdown',e=>{if(view.inputDisabled||aimPointer!==null||b.disabled)return;e.preventDefault();aimPointer=e.pointerId;aimButton=b;b.setPointerCapture(e.pointerId);b.classList.add('active');$('#aim-cancel').hidden=false;moveAim(e);});listen(b,'pointermove',e=>{if(e.pointerId===aimPointer)moveAim(e);});listen(b,'pointerup',e=>{if(e.pointerId!==aimPointer)return;const aim=view.aim;if(aim&&!aim.cancelled&&!view.inputDisabled){const cmd={type:'ability',slot:aim.slot};if(aim.slot===1&&(aim.dx||aim.dy)){cmd.x=hero.x+aim.dx*aim.range;cmd.y=hero.y+aim.dy*aim.range;}client.command(cmd);}cancelAim();});for(const event of ['pointercancel','lostpointercapture'])listen(b,event,e=>{if(e.pointerId===aimPointer)cancelAim();});listen(b,'click',e=>{if(e.detail===0&&!view.inputDisabled)client.command({type:'ability',slot:Number(b.dataset.slot)});});});
  const stopAll=()=>{stop();stopAttack();cancelAim();};listen(window,'blur',stopAll);listen(document,'visibilitychange',()=>{if(document.hidden)stopAll();});listen($('#help'),'click',stopAll);listen($('#leave'),'click',stopAll);listen(window,'keydown',e=>{if(e.key==='Escape')stopAll();});listen(root,'contextmenu',e=>{if(e.target.closest('.combat-button,.joystick'))e.preventDefault();});
  const movement=setInterval(()=>{if(stick.active&&hero&&hero.hp>0&&!view.inputDisabled)sendSteer();},50);
  const update=(state,session,status,error)=>{
    currentSession=status==='disconnected'?null:session;hero=state?.actors.find(a=>a.id===currentSession?.playerId);const playing=Boolean(state&&currentSession);$('#join-screen').hidden=playing;document.body.classList.toggle('join-active',!playing);if(playing){joining=false;$('#join').disabled=false;$('#join').textContent=(roomInput.value.trim()?'Join duel':'Create duel');}
    if(!error)lastError='';if(error&&error!==lastError){lastError=error;message(error,true);$('#join-error').textContent=error;joining=false;$('#join').disabled=false;$('#join').textContent=(roomInput.value.trim()?'Join duel':'Create duel');}if(!state||!currentSession){sync();return;}
    $('#connection').textContent=status||'Connected';$('#room-code').textContent=session.room;const sec=Math.floor(state.elapsed);$('#clock').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;
    for(const t of ['blue','red']){const c=state.structures.find(s=>s.kind==='core'&&s.team===t);$(`#${t}-core`).textContent=c?`${Math.ceil(c.hp/c.maxHp*100)}%`:'—';}
    if(hero){const bank=state.bank[hero.team];$('#wood').textContent=Math.floor(bank.wood);$('#gold').textContent=Math.floor(bank.gold);$('#hero-name').textContent=hero.name;$('#hero-class').textContent=hero.hero;$('#hp-bar').style.width=`${Math.max(0,hero.hp/hero.maxHp*100)}%`;$('.health').setAttribute('aria-valuenow',String(Math.round(hero.hp/hero.maxHp*100)));$('#hp-value').textContent=hero.hp>0?`${Math.ceil(hero.hp)} / ${hero.maxHp} HP`:`Respawn ${Math.max(0,Math.ceil(hero.respawnAt-state.elapsed))}s`;$('#kills').textContent=`${hero.kills} defeats`;
      for(const team of ['blue','red'])$(`#${team}-score`).textContent=state.actors.filter(a=>a.team===team&&a.kind==='hero').reduce((n,a)=>n+a.kills,0);
      root.querySelectorAll('[data-slot]').forEach(b=>{const slot=Number(b.dataset.slot),name=skills[hero.hero][slot-1][0],cd=Math.max(0,Math.ceil(hero.abilityCooldowns?.[slot-1]||(slot===1?hero.abilityCooldown:0)));b.querySelector('.skill-name').textContent=name;b.setAttribute('aria-label',`Ability ${slot}: ${name}`);b.title=`${skills[hero.hero][slot-1][2]} ${slot===1?'Drag to aim.':'Tap to cast.'}`;b.classList.toggle('sprinting',slot===2&&hero.sprintUntil>state.elapsed);b.querySelector('.cooldown').textContent=cd;b.querySelector('.cooldown').hidden=cd===0;b.disabled=cd>0||hero.hp<=0;});
      const regen=$('[data-action="regen"]'),regenCd=Math.max(0,Math.ceil(hero.regenCooldown||0));regen.querySelector('.cooldown').textContent=regenCd;regen.querySelector('.cooldown').hidden=regenCd===0;regen.disabled=regenCd>0||hero.hp<=0;const recalling=Math.max(0,(hero.recallUntil||0)-state.elapsed);$('[data-action="recall"] span').textContent=recalling>0?`${recalling.toFixed(1)}s`:'Recall';$('[data-action="recall"]').classList.toggle('active',recalling>0);attack.disabled=hero.hp<=0;
      const companion=state.actors.find(a=>a.ownerId===hero.id&&a.kind==='companion');$('#companion-name').textContent=companion?.companion||'Companion';$('#companion-state').textContent=companion?`${companion.order} · ${Math.ceil(companion.hp)} HP`:'Returning to the realm';root.querySelectorAll('[data-order]').forEach(b=>b.classList.toggle('active',b.dataset.order===companion?.order));if(hero.lastAction&&hero.lastAction!==latestAction&&!view.buildMode){latestAction=hero.lastAction;message(hero.lastAction);}}
    const cast=$('#cast-status');
    const recallRemaining=Math.max(0,(hero?.recallUntil||0)-state.elapsed);
    const dead=hero?.hp<=0,remaining=dead?Math.max(0,hero.respawnAt-state.elapsed):recallRemaining;
    cast.hidden=!dead&&!recallRemaining;
    cast.classList.toggle('death-status',dead);
    cast.querySelector('strong').textContent=dead?'Returning to battle':'Recalling';
    cast.querySelector('span').textContent=dead?`Respawn in ${Math.ceil(remaining)}s`:`${remaining.toFixed(1)}s · move to cancel`;
    cast.querySelector('i').style.width=`${Math.max(0,Math.min(100,(1-remaining/(dead?10:3))*100))}%`;
    const feedback=$('#combat-feedback'),damage=hero?.lastDamage;
    const protectedFor=(hero?.protectedUntil||0)-state.elapsed;
    feedback.textContent=hero?.hp<=0?(damage?`Defeated by ${damage.sourceName} · last hit ${Math.ceil(damage.amount)}`:'Defeated · returning to base'):protectedFor>0?`Spawn protection · ${Math.ceil(protectedFor)}s`:damage&&state.elapsed-damage.at<3?`${damage.sourceName} · −${Math.ceil(damage.amount)} HP`:'';
    feedback.hidden=!feedback.textContent;
    if(state.phase==='playing')resultShown=false;
    if(state.phase==='finished'&&!resultShown){resultShown=true;$('#result-title').textContent=hero?.team===state.winner?'The realm is yours.':'Your core has fallen.';$('#result-body').textContent=`${state.winner==='blue'?'Blue':'Red'} won in ${$('#clock').textContent}. Gathered ${hero?.gathered||0} resources, defeated ${hero?.kills||0} enemies.`;$('#results').showModal();}sync();
  };
  setLoadState({});sync();return {getView:()=>view,update,setLoadState,setReady:ready=>setLoadState({playable:ready}),destroy:()=>{stopAll();clearInterval(movement);clearTimeout(messageTimer);listeners.forEach(fn=>fn());if(loadPanel)document.body.append(loadPanel);root.innerHTML='';}};
}
