// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ControlCommandReducer from "../control_command_reducer";
import IssueCommandReducer from "../issue_command_reducer";
import JoinMatchReducer from "../join_match_reducer";
import RestartMatchReducer from "../restart_match_reducer";

export type ControlCommandParams = __Infer<typeof ControlCommandReducer>;
export type IssueCommandParams = __Infer<typeof IssueCommandReducer>;
export type JoinMatchParams = __Infer<typeof JoinMatchReducer>;
export type RestartMatchParams = __Infer<typeof RestartMatchReducer>;

